# Generated by Django 3.2 on 2022-11-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='first_name',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
