# Generated by Django 3.2 on 2022-11-28 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20221126_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='first_name',
            field=models.CharField(default='defaultname', max_length=99),
            preserve_default=False,
        ),
    ]
