# Generated by Django 3.2 on 2022-11-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_preview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview_image',
            new_name='image_preview',
        ),
    ]
